/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 glass_06.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Glass(props) {
  const { nodes, materials } = useGLTF('/3d-objects/aquarium-glass/glass_06.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.008']} position={[1.675, 0.603, 0]} />
    </group>
  )
}

useGLTF.preload('/3d-objects/aquarium-glass/glass_06.gltf')
