/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Aquarium(props) {
  const { nodes, materials } = useGLTF('/3d-objects/aquarium-test/glass7.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-3.292, 0, 0]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['Material.001']}
        position={[1.856, 0, 0]}
        scale={[0.574, 0.643, 0.654]}
      />
    </group>
  )
}

useGLTF.preload('/3d-objects/aquarium-test/glass7.glb')